// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_index: dynamic(() => import("./BlogIndex")),
  book_index: dynamic(() => import("./BookIndex")),
  hero: dynamic(() => import("./Hero")),
  project_index: dynamic(() => import("./ProjectIndex")),
  text_block: dynamic(() => import("./TextBlock")),
};
